# Generated by Django 5.1.3 on 2024-11-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_target_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='app.mission'),
        ),
    ]
