# Generated by Django 5.1.3 on 2024-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_target_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='target',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
